### ISSUE TITLE
Data preprocessing and analysis

### ISSUE THREAD

**Issue by ARTC-Doris** [artc-dsc/Tasks#32]

**Comment by ZengyuCao-ARTC** [comment]
## TODO List in plan
### Processing - demand (sales) _completed by Sep_
- [ ] SKU master ID mapping (different scenarios: promo/discontinued/case config/Pack Type)
- [ ] resampling to Daily/Weekly/Monthly time series per SKU/product family
### Processing - external factor _completed by Sep_
- [ ] weather - aggregate to weekly monthly (required geo-location mapping plus taking 10%min, 90%max, mean, median etc. )
- [ ] promotion - depends on discrete event or periodic series to handle differently 
- [ ] other macro trends - only analysis
### Analysis _completed by Nov_
- [ ] SKU master data segmentation, e.g. ABC, product family
- [ ] SKU demand profiling, e.g. min/max/std/forecastabilities/seasonal parameters etc. 
- [ ] correlation analysis between SKU-external factor and SKU-SKU
- [ ] segmenation based on characteristics
- [ ] other ad-hoc analysis



## Notes
Background: North India, 110SKU * 9 facilities, 3 yrs sales
Requirement: monthly rolling forecast to next 12 month
 
@ARTC-Doris Please review and comment.

**Comment by ARTC-Doris** [comment]
@ZengyuCao-ARTC timeline need to be changed a bit to align with milestone review. Please see if any difficulty to meet the proposed timeline as below.

1. Processing - demand (sales) completed by Jun
2. Processing - external factor completed by Jul
3. Analysis completed by Aug (Milestone 1)

Segmentation relies on demand data, is it possible to conduct initial study after step 1, and finetune in Step 3?

**Comment by ZengyuCao-ARTC** [comment]
> @ZengyuCao-ARTC timeline need to be changed a bit to align with milestone review. Please see if any difficulty to meet the proposed timeline as below.
> 
> 1. Processing - demand (sales) completed by Jun
> 2. Processing - external factor completed by Jul (provided to received TCCC promotion data by end of June)
> 3. Analysis completed by Aug (Milestone 1)
> 
> Segmentation relies on demand data, is it possible to conduct initial study after step 1, and finetune in Step 3?

1&2 okay, for analysis I will prioritize those required by model dev. Analytic insight will be delivered first, and API coding & integration might need more time. 
Agree that segmentation can be conducted stage-by-stage. What are step 1 & 3 referring to?

**Comment by ARTC-Doris** [comment]
- Right, milestone 1 is for analytical insights review, API coding and integration can be completed by Sep and Nov sequentially.
- Please ignore the "step1&3", basically I was trying to say that "segmentation can be conducted stage-by-stage"
